"""Equation metadata and registry primitives."""

from .geodesy import (
    CartesianVector3,
    GeocentricPosition,
    GeodeticPosition,
    VelocityAngles,
    ecfc_to_geocentric_position,
    ecfc_to_geocentric_velocity,
    ecfc_to_geodetic_position,
    ecfc_to_geodetic_velocity,
    geocentric_position_to_ecfc,
    geocentric_unit_vectors,
    geocentric_velocity_angles_from_components,
    geocentric_velocity_components_from_angles,
    geocentric_velocity_to_ecfc,
    geodetic_position_to_ecfc,
    geodetic_surface_normal_distance,
    geodetic_unit_vectors,
    geodetic_velocity_angles_from_components,
    geodetic_velocity_components_from_angles,
    geodetic_velocity_to_ecfc,
    polar_radius_from_equatorial_radius,
)
from .radar import (
    RadarAngles,
    RadarObservation,
    radar_azimuth_elevation,
    radar_line_of_sight_unit_vector,
    radar_observation,
    radar_range_rate,
    radar_relative_position,
)
from .registry import (
    Equation,
    EquationImplementationStatus,
    EquationRegistry,
    implementation_summary,
    load_equation_registry,
    registry,
)

__all__ = [
    "CartesianVector3",
    "Equation",
    "EquationImplementationStatus",
    "EquationRegistry",
    "GeocentricPosition",
    "GeodeticPosition",
    "VelocityAngles",
    "ecfc_to_geocentric_position",
    "ecfc_to_geocentric_velocity",
    "ecfc_to_geodetic_velocity",
    "ecfc_to_geodetic_position",
    "geocentric_position_to_ecfc",
    "geocentric_unit_vectors",
    "geocentric_velocity_angles_from_components",
    "geocentric_velocity_components_from_angles",
    "geocentric_velocity_to_ecfc",
    "geodetic_position_to_ecfc",
    "geodetic_surface_normal_distance",
    "geodetic_unit_vectors",
    "geodetic_velocity_angles_from_components",
    "geodetic_velocity_components_from_angles",
    "geodetic_velocity_to_ecfc",
    "implementation_summary",
    "load_equation_registry",
    "polar_radius_from_equatorial_radius",
    "RadarObservation",
    "RadarAngles",
    "radar_azimuth_elevation",
    "radar_line_of_sight_unit_vector",
    "radar_observation",
    "radar_range_rate",
    "radar_relative_position",
    "registry",
]
