from __future__ import annotations

from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
REQUIRED = [
    ROOT / "README.md",
    ROOT / "AGENTS.md",
    ROOT / "scripts" / "bootstrap.py",
    ROOT / "scripts" / "doctor.py",
    ROOT / "tools" / "dev.py",
    ROOT / "pyproject.toml",
    ROOT / "docs" / "BUILDING.md",
    ROOT / "docs" / "manual" / "README.md",
    ROOT / "docs" / "manual" / "CODEX_HANDOFF.md",
    ROOT / "docs" / "manual" / "RECONSTRUCTION_README.md",
    ROOT / "docs" / "qa" / "VISUAL_QA_REPORT.md",
    ROOT / "manual" / "manual.tex",
    ROOT / "manual" / "styles" / "taos.sty",
    ROOT / "manual" / "math" / "matrices" / "rotations.tex",
    ROOT / "manual" / "frontmatter" / "title.tex",
    ROOT / "manual" / "chapters" / "01_introduction.tex",
    ROOT / "manual" / "chapters" / "02_methods.tex",
    ROOT / "manual" / "chapters" / "03_table_files.tex",
    ROOT / "manual" / "chapters" / "04_problem_files.tex",
    ROOT / "metadata" / "progress.yaml",
    ROOT / "metadata" / "figures.csv",
    ROOT / "metadata" / "tables.csv",
    ROOT / "metadata" / "equations.csv",
    ROOT / "metadata" / "equations_provenance.csv",
    ROOT / "metadata" / "equations_provenance.json",
    ROOT / "metadata" / "source_page_coverage.csv",
    ROOT / "metadata" / "table_types.yaml",
    ROOT / "metadata" / "table_math_operations.yaml",
    ROOT / "metadata" / "state_variables_chapter3.yaml",
    ROOT / "metadata" / "coordinate_systems_chapter2.yaml",
    ROOT / "metadata" / "state_variables_chapter2_coordinates.yaml",
    ROOT / "metadata" / "coordinate_transforms_chapter2.yaml",
    ROOT / "metadata" / "aerodynamic_angles_chapter2.yaml",
    ROOT / "metadata" / "rotation_matrices_chapter2.yaml",
    ROOT / "metadata" / "editorial_notes_chapter2.yaml",
    ROOT / "metadata" / "equations_of_motion_chapter2.yaml",
    ROOT / "metadata" / "state_variables_chapter2_dynamics.yaml",
    ROOT / "metadata" / "acceleration_models_chapter2.yaml",
    ROOT / "metadata" / "state_variables_chapter2_acceleration.yaml",
    ROOT / "metadata" / "trajectory_execution_chapter2.yaml",
    ROOT / "metadata" / "search_algorithms_chapter2.yaml",
    ROOT / "metadata" / "optimization_model_chapter2.yaml",
    ROOT / "metadata" / "problem_blocks_chapter4.yaml",
    ROOT / "metadata" / "guidance_rules_chapter4.yaml",
    ROOT / "metadata" / "chapter4_examples.yaml",
    ROOT / "metadata" / "references.yaml",
    ROOT / "metadata" / "index_entries.yaml",
    ROOT / "metadata" / "distribution.yaml",
    ROOT / "metadata" / "legacy_inbox_manifest.json",
    ROOT / "metadata" / "legacy_grammar_registry.json",
    ROOT / "metadata" / "diplomatic_transcription_chapter4.yaml",
    ROOT / "metadata" / "diplomatic_transcription_chapter4_v17.yaml",
    ROOT / "metadata" / "diplomatic_transcription_chapter4_v18.yaml",
    ROOT / "metadata" / "diplomatic_transcription_chapter4_v19.yaml",
    ROOT / "metadata" / "editorial_notes_chapter4.yaml",
    ROOT / "metadata" / "editorial_notes_backmatter.yaml",
    ROOT / "metadata" / "fixture_provenance.yaml",
    ROOT / "examples" / "chapter03" / "orbus-mdt.tbl",
    ROOT / "examples" / "chapter03" / "recruits-thr.tbl",
    ROOT / "examples" / "chapter03" / "reentry-ca-excerpt.tbl",
    ROOT / "examples" / "chapter03" / "stmi-full.tbl",
    ROOT / "examples" / "chapter03" / "stmi-simple.tbl",
    ROOT / "examples" / "chapter04" / "ballistic-reentry.prb",
    ROOT / "examples" / "chapter04" / "ballistic-rocket.prb",
    ROOT / "examples" / "chapter04" / "air-launched-intercept.prb",
    ROOT / "examples" / "chapter04" / "ground-launched-intercept.prb",
    ROOT / "examples" / "chapter04" / "ballistic-reentry-printout.txt",
    ROOT / "examples" / "chapter04" / "ballistic-reentry-summary.txt",
    ROOT / "examples" / "chapter04" / "ballistic-rocket-printout.txt",
    ROOT / "examples" / "chapter04" / "air-intercept-printout.txt",
    ROOT / "examples" / "chapter04" / "ground-intercept-printout.txt",
    ROOT / "examples" / "chapter04" / "problem-output-example.txt",
    ROOT / "examples" / "chapter04" / "problem-printout-example.txt",
    ROOT / "examples" / "chapter04" / "summary-printout-example.txt",
    ROOT / "examples" / "chapter04" / "trajectory-output-example.txt",
    ROOT / "examples" / "chapter04" / "trajectory-printout-example.txt",
    ROOT / "examples" / "chapter04" / "egs-database-example.txt",
    ROOT / "examples" / "taos1995" / "README.md",
    ROOT / "examples" / "taos1995" / "grammar" / "example.taos",
    ROOT / "docs" / "grammar" / "README.md",
    ROOT / "docs" / "grammar" / "legacy-toolkit-review.md",
    ROOT / "docs" / "grammar" / "legacy-inventory.md",
    ROOT / "tools" / "check_chapter02_part1.py",
    ROOT / "tools" / "check_chapter02_part2.py",
    ROOT / "tools" / "check_chapter02_section22.py",
    ROOT / "tools" / "check_chapter02_section23.py",
    ROOT / "tools" / "check_chapter02_section24.py",
    ROOT / "tools" / "check_chapter02_section25.py",
    ROOT / "tools" / "check_chapter02_section26.py",
    ROOT / "tools" / "check_chapter04.py",
    ROOT / "tools" / "check_chapter04_diplomatic.py",
    ROOT / "tools" / "check_chapter04_diplomatic_v17.py",
    ROOT / "tools" / "check_chapter04_diplomatic_v18.py",
    ROOT / "tools" / "check_chapter04_residual_v19.py",
    ROOT / "tools" / "check_backmatter.py",
    ROOT / "tools" / "check_equation_provenance.py",
    ROOT / "tools" / "check_manifest.py",
    ROOT / "tools" / "check_pdf_interoperability.py",
    ROOT / "tools" / "check_source_fidelity.py",
    ROOT / "tools" / "check_taos_fixtures.py",
    ROOT / "tools" / "audit_legacy_inbox.py",
    ROOT / "tools" / "check_legacy_closure.py",
    ROOT / "tools" / "check_visual_sweep.py",
    ROOT / "tools" / "audit_equation_provenance.py",
    ROOT / "tools" / "audit_chapter04_diplomatic.py",
    ROOT / "tools" / "audit_chapter04_diplomatic_v17.py",
    ROOT / "tools" / "audit_chapter04_diplomatic_v18.py",
    ROOT / "tools" / "audit_chapter04_residual_v19.py",
    ROOT / "tools" / "audit_source_fidelity.py",
    ROOT / "tools" / "build_handoff_bundle.py",
    ROOT / "tools" / "generate_appendix_output_variables.py",
    ROOT / "tools" / "generate_backmatter.py",
    ROOT / "tools" / "generate_fixture_validation_pdf.py",
    ROOT / "tools" / "generate_visual_qa.py",
    ROOT / "tools" / "normalize_pdf.py",
    ROOT / "src" / "taoryx" / "__init__.py",
    ROOT / "src" / "taoryx" / "equations" / "__init__.py",
    ROOT / "src" / "taoryx" / "equations" / "registry.py",
    ROOT / "src" / "taoryx" / "grammar" / "__init__.py",
    ROOT / "src" / "taoryx" / "simulation" / "__init__.py",
    ROOT / "src" / "taoryx" / "simulation" / "contracts.py",
    ROOT / "src" / "taoryx" / "simulation" / "runner.py",
    ROOT / "src" / "taoryx" / "language" / "__init__.py",
    ROOT / "src" / "taoryx" / "language" / "cli.py",
    ROOT / "src" / "taoryx" / "language" / "diagnostics.py",
    ROOT / "src" / "taoryx" / "language" / "expressions.py",
    ROOT / "src" / "taoryx" / "language" / "models.py",
    ROOT / "src" / "taoryx" / "language" / "problem_parser.py",
    ROOT / "src" / "taoryx" / "language" / "semantic_validation.py",
    ROOT / "src" / "taoryx" / "language" / "table_parser.py",
    ROOT / "src" / "taoryx" / "language" / "_legacy_table.py",
    ROOT / "src" / "taoryx" / "language" / "lossless.py",
    ROOT / "src" / "taoryx" / "language" / "ingest.py",
    ROOT / "src" / "taoryx" / "language" / "grammar_contracts.py",
    ROOT / "tests" / "parser" / "test_all_block_dispatch.py",
    ROOT / "tests" / "parser" / "test_lossless_baseline.py",
    ROOT / "tests" / "parser" / "test_ingestion_route.py",
    ROOT / "tests" / "parser" / "test_grammar_contracts.py",
    ROOT / "tests" / "parser" / "test_problem_framing.py",
    ROOT / "tests" / "unit" / "test_simulation_kernel.py",
    ROOT / "tests" / "parser" / "test_equation_provenance.py",
    ROOT / "tests" / "parser" / "test_expressions.py",
    ROOT / "tests" / "parser" / "test_problem_parser.py",
    ROOT / "tests" / "parser" / "test_table_parser.py",
    ROOT / "tests" / "unit" / "test_equations.py",
]


def main() -> None:
    missing = [path for path in REQUIRED if not path.exists()]
    if missing:
        formatted = "\n".join(f"- {path.relative_to(ROOT)}" for path in missing)
        raise SystemExit(f"Missing required reconstruction files:\n{formatted}")
    ####
    print(f"Scaffold check passed: {len(REQUIRED)} required files found.")
####


if __name__ == "__main__":
    main()
####
