from __future__ import annotations

import hashlib
import json
from collections import Counter
from pathlib import Path
from typing import Any

import yaml
from taos_fixture_parser import (
    ProblemParseResult,
    TableParseResult,
    parse_problem_file,
    parse_table_file,
    summarize_issues,
)

ROOT = Path(__file__).resolve().parents[1]
PROVENANCE = ROOT / "metadata" / "fixture_provenance.yaml"
JSON_REPORT = ROOT / "qa" / "fixture_validation.json"
MARKDOWN_REPORT = ROOT / "qa" / "fixture_validation.md"


def _load_yaml(path: Path) -> Any:
    with path.open(encoding="utf-8") as handle:
        return yaml.safe_load(handle)
    ####
####


def _sha256(path: Path) -> str:
    digest = hashlib.sha256()
    with path.open("rb") as handle:
        for chunk in iter(lambda: handle.read(1024 * 1024), b""):
            digest.update(chunk)
        ####
    ####
    return digest.hexdigest()
####


def _relative(path: Path) -> str:
    return path.relative_to(ROOT).as_posix()
####


def _table_payload(result: TableParseResult) -> dict[str, Any]:
    return {
        "path": _relative(Path(result.path).resolve()),
        "executable_complete": result.executable_complete,
        "tables": [
            {
                "name": table.name,
                "type": table.table_type,
                "format": table.format,
                "independent_variables": table.independent_variables,
                "operation_count": len(table.operations),
                "assignment_count": len(table.assignments) + sum(len(operation.assignments) for operation in table.operations),
                "omission_lines": table.omissions,
            }
            for table in result.tables
        ],
        "issues": [issue.model_dump() for issue in result.issues],
        "issue_counts": summarize_issues(result.issues),
    }
####


def _problem_payload(result: ProblemParseResult) -> dict[str, Any]:
    problem = result.problem
    return {
        "path": _relative(Path(result.path).resolve()),
        "problem_name": problem.name if problem is not None else None,
        "trajectory_count": len(problem.trajectories) if problem is not None else 0,
        "segment_count": sum(len(trajectory.segments) for trajectory in problem.trajectories) if problem is not None else 0,
        "problem_block_count": len(problem.problem_blocks) if problem is not None else 0,
        "table_references": result.table_references,
        "issues": [issue.model_dump() for issue in result.issues],
        "issue_counts": summarize_issues(result.issues),
    }
####


def _render_markdown(report: dict[str, Any]) -> str:
    summary = report["summary"]
    lines: list[str] = [
        "# TAOS fixture parser-validation report",
        "",
        "This report is generated by the repository's line-aware TAOS table/problem parsers. "
        "It validates the extracted documentation fixtures structurally and semantically; it does not claim runtime execution against the historical TAOS 96.0 binary.",
        "",
        "## Summary",
        "",
        "| Metric | Result |",
        "|---|---:|",
        f"| `.tbl` fixtures parsed | {summary['table_fixture_count']} |",
        f"| `.prb` fixtures parsed | {summary['problem_fixture_count']} |",
        f"| Tables represented | {summary['table_count']} |",
        f"| Trajectories represented | {summary['trajectory_count']} |",
        f"| Segments represented | {summary['segment_count']} |",
        f"| Parser errors | {summary['issue_counts']['error']} |",
        f"| Warnings | {summary['issue_counts']['warning']} |",
        f"| Informational notes | {summary['issue_counts']['note']} |",
        "",
        "## Table fixtures",
        "",
        "| Fixture | Parsed table(s) | Status | Issues |",
        "|---|---|---|---|",
    ]
    for item in report["table_fixtures"]:
        table_names = ", ".join(f"`{table['name']}` ({table['format']})" for table in item["tables"])
        status = "executable-complete" if item["executable_complete"] else "documentation excerpt"
        counts = item["issue_counts"]
        issue_text = f"{counts['error']} error, {counts['warning']} warning, {counts['note']} note"
        lines.append(f"| `{item['path']}` | {table_names} | {status} | {issue_text} |")
    ####
    lines.extend(
        [
            "",
            "## Problem fixtures",
            "",
            "| Fixture | Problem | Trajectories | Segments | Referenced tables | Issues |",
            "|---|---|---:|---:|---:|---|",
        ]
    )
    for item in report["problem_fixtures"]:
        counts = item["issue_counts"]
        issue_text = f"{counts['error']} error, {counts['warning']} warning, {counts['note']} note"
        lines.append(
            f"| `{item['path']}` | `{item['problem_name']}` | {item['trajectory_count']} | "
            f"{item['segment_count']} | {len(item['table_references'])} | {issue_text} |"
        )
    ####
    lines.extend(
        [
            "",
            "## Source-preserved findings",
            "",
            "- The Orbus `tmark` array contains consecutive `0.00` entries. This is present in the printed source on manual page 3-26, even though Section 3.4 says duplicate independent values are not allowed. The parser reports it as a warning rather than silently changing the fixture.",
            "- `reentry-ca-excerpt.tbl` contains the manual's explicit ellipsis. The parser accepts the syntax as a documentation excerpt but marks it non-executable-complete.",
            "- Table references not bundled with a worked example are treated as external dependencies, not syntax failures.",
            "",
            "## Validation boundary",
            "",
            "The parsers check hierarchy, token structure, table cardinality, independent-variable ordering, trajectory and segment uniqueness, start/goto targets, inherited initial-state references, indexed trajectory references, survey/optimization parameter definitions, and `*when` conditions/actions. Numerical trajectory results remain unverified without the historical executable or an independent compatible implementation.",
            "",
        ]
    )
    return "\n".join(lines)
####


def main() -> None:
    metadata = _load_yaml(PROVENANCE)["fixture_validation"]
    fixture_records = list(metadata["fixtures"])
    table_results: list[TableParseResult] = []
    problem_results: list[ProblemParseResult] = []
    hashes: dict[str, str] = {}
    expected_paths = {str(item["path"]) for item in fixture_records}
    actual_paths = {
        _relative(path)
        for path in [*ROOT.glob("examples/**/*.tbl"), *ROOT.glob("examples/**/*.prb")]
    }
    if expected_paths != actual_paths:
        raise SystemExit(
            "Fixture provenance and repository contents differ. Missing metadata: "
            f"{sorted(actual_paths - expected_paths)}; missing files: {sorted(expected_paths - actual_paths)}"
        )
    ####
    for record in fixture_records:
        path = ROOT / str(record["path"])
        hashes[_relative(path)] = _sha256(path)
        if record["language"] == "tbl":
            result = parse_table_file(path)
            table_results.append(result)
            expected_status = str(record["expected_status"])
            if expected_status == "documentation_excerpt" and result.executable_complete:
                raise SystemExit(f"{path} should be a documentation excerpt.")
            ####
            if expected_status.startswith("executable_complete") and not result.executable_complete:
                raise SystemExit(f"{path} should be executable-complete.")
            ####
        elif record["language"] == "prb":
            problem_results.append(parse_problem_file(path))
        else:
            raise SystemExit(f"Unknown fixture language {record['language']!r}.")
        ####
    ####
    all_issues = [
        *[issue for result in table_results for issue in result.issues],
        *[issue for result in problem_results for issue in result.issues],
    ]
    issue_counts = Counter(issue.severity for issue in all_issues)
    if issue_counts.get("error", 0):
        messages = [
            f"{issue.code}: {issue.message}"
            for issue in all_issues
            if issue.severity == "error"
        ]
        raise SystemExit("Fixture validation errors:\n" + "\n".join(messages))
    ####
    bundled_table_names = {
        table.name
        for result in table_results
        for table in result.tables
    }
    external_dependencies = sorted(
        {
            reference
            for result in problem_results
            for reference in result.table_references
            if reference not in bundled_table_names
        }
    )
    report: dict[str, Any] = {
        "schema_version": 1,
        "summary": {
            "table_fixture_count": len(table_results),
            "problem_fixture_count": len(problem_results),
            "table_count": sum(len(result.tables) for result in table_results),
            "trajectory_count": sum(len(result.problem.trajectories) for result in problem_results if result.problem is not None),
            "segment_count": sum(
                len(trajectory.segments)
                for result in problem_results
                if result.problem is not None
                for trajectory in result.problem.trajectories
            ),
            "issue_counts": {
                severity: issue_counts.get(severity, 0)
                for severity in ("error", "warning", "note")
            },
            "bundled_table_names": sorted(bundled_table_names),
            "external_table_dependencies": external_dependencies,
        },
        "table_fixtures": [_table_payload(result) for result in table_results],
        "problem_fixtures": [_problem_payload(result) for result in problem_results],
        "sha256": hashes,
    }
    JSON_REPORT.parent.mkdir(parents=True, exist_ok=True)
    JSON_REPORT.write_text(json.dumps(report, indent=2, sort_keys=True) + "\n", encoding="utf-8")
    MARKDOWN_REPORT.write_text(_render_markdown(report), encoding="utf-8")
    print(
        "TAOS fixture validation passed: "
        f"{len(table_results)} table fixtures, {len(problem_results)} problem fixtures, "
        f"{issue_counts.get('warning', 0)} warning(s), {issue_counts.get('note', 0)} note(s)."
    )
####


if __name__ == "__main__":
    main()
####
