from __future__ import annotations

from pathlib import Path
from typing import Any

import yaml

ROOT = Path(__file__).resolve().parents[1]
REFERENCES_METADATA = ROOT / "metadata" / "references.yaml"
INDEX_METADATA = ROOT / "metadata" / "index_entries.yaml"
DISTRIBUTION_METADATA = ROOT / "metadata" / "distribution.yaml"
REFERENCES_OUTPUT = ROOT / "backmatter" / "references_generated.tex"
INDEX_OUTPUT = ROOT / "backmatter" / "index_generated.tex"
DISTRIBUTION_OUTPUT = ROOT / "backmatter" / "distribution_generated.tex"


def _load_yaml(path: Path) -> Any:
    with path.open() as handle:
        return yaml.safe_load(handle)
    ####
####


def _write_references() -> None:
    payload = _load_yaml(REFERENCES_METADATA)["references"]
    entries = list(payload["entries"])
    by_page: dict[int, list[dict[str, Any]]] = {}
    for entry in entries:
        by_page.setdefault(int(entry["source_pdf_page"]), []).append(entry)
    ####

    lines = [
        "% Generated from metadata/references.yaml.",
        "% Do not edit this file directly; run tools/generate_backmatter.py.",
        r"\begingroup",
        r"\footnotesize",
    ]
    for page_index, source_page in enumerate([294, 295]):
        page_entries = by_page[source_page]
        if page_index == 0:
            lines.extend(
                [
                    r"\taosbackmattertitle{References}",
                    r"\begin{enumerate}[label=\arabic*.,leftmargin=1.75em,labelsep=0.45em,itemsep=0.58\baselineskip,topsep=0.5\baselineskip]",
                ]
            )
        else:
            lines.extend(
                [
                    r"\clearpage",
                    r"\begin{enumerate}[label=\arabic*.,leftmargin=1.75em,labelsep=0.45em,itemsep=0.64\baselineskip,topsep=0pt,start=13]",
                ]
            )
        ####
        lines.append(f"% Source PDF page {source_page}; source manual page Ref-{source_page - 293}.")
        for entry in page_entries:
            number = int(entry["number"])
            text = str(entry["entry_latex"])
            lines.append(rf"\hypertarget{{taos-ref-{number}}}{{}}\item {text}")
        ####
        lines.append(r"\end{enumerate}")
    ####
    lines.extend([r"\endgroup", ""])
    REFERENCES_OUTPUT.write_text("\n".join(lines))
####


def _reference_text(item: dict[str, Any]) -> str:
    references = list(item.get("references", []))
    return ", ".join(str(value) for value in references)
####


def _index_line(item: dict[str, Any]) -> str:
    kind = str(item["type"])
    text = str(item["text"])
    references = _reference_text(item)
    commands = {
        "letter": r"\taosindexletter",
        "entry": r"\taosindexentry",
        "subentry": r"\taosindexsubentry",
        "variable": r"\taosindexvariable",
        "subvariable": r"\taosindexsubvariable",
        "subblock": r"\taosindexsubblock",
    }
    if kind not in commands:
        raise ValueError(f"Unknown index item type: {kind}")
    ####
    command = commands[kind]
    if kind == "letter":
        return rf"{command}{{{text}}}"
    ####
    return rf"{command}{{{text}}}{{{references}}}"
####


def _write_index() -> None:
    payload = _load_yaml(INDEX_METADATA)["index"]
    pages = list(payload["pages"])
    lines = [
        "% Generated from metadata/index_entries.yaml.",
        "% Do not edit this file directly; run tools/generate_backmatter.py.",
    ]
    for page_index, page in enumerate(pages):
        if page_index > 0:
            lines.append(r"\clearpage")
        ####
        source_page = int(page["source_pdf_page"])
        manual_page = str(page["source_manual_page"])
        lines.append(f"% Source PDF page {source_page}; source manual page {manual_page}.")
        if bool(page["show_title"]):
            lines.append(r"\taosbackmattertitle{Index}")
        ####
        lines.extend(
            [
                r"\begingroup",
                r"\fontsize{8.6}{10.35}\selectfont",
                r"\noindent\begin{minipage}[t]{0.467\textwidth}",
                r"\raggedright",
            ]
        )
        lines.extend(_index_line(item) for item in page["left"])
        lines.extend(
            [
                r"\end{minipage}\hfill%",
                r"\begin{minipage}[t]{0.467\textwidth}",
                r"\raggedright",
            ]
        )
        lines.extend(_index_line(item) for item in page["right"])
        lines.extend([r"\end{minipage}", r"\endgroup"])
    ####
    blank = payload["blank_page"]
    lines.extend(
        [
            r"\clearpage",
            f"% Source PDF page {blank['source_pdf_page']}; source manual page {blank['source_manual_page']}.",
            r"\thispagestyle{plain}",
            r"\null",
            r"\vfill",
            r"\begin{center}",
            rf"  \itshape {blank['text']}",
            r"\end{center}",
            r"\vfill",
            r"\null",
            "",
        ]
    )
    INDEX_OUTPUT.write_text("\n".join(lines))
####


def _distribution_recipient(entry: dict[str, Any]) -> str:
    if "recipient_lines" in entry:
        lines = [str(value) for value in entry["recipient_lines"]]
        return r"\begin{tabular}[t]{@{}l@{}}" + r" \\ ".join(lines) + r"\end{tabular}"
    ####
    return str(entry["recipient"])
####


def _write_distribution() -> None:
    payload = _load_yaml(DISTRIBUTION_METADATA)["distribution"]
    entries = list(payload["entries"])
    lines = [
        "% Generated from metadata/distribution.yaml.",
        "% Do not edit this file directly; run tools/generate_backmatter.py.",
        "% Source PDF page 306; source manual page Dist-1.",
        r"\taosbackmattertitle{Distribution}",
        r"\begingroup",
        r"\small",
        r"\renewcommand{\arraystretch}{1.06}",
        r"\begin{center}",
        r"\begin{tabular}{@{}r@{\hspace{1.0cm}}l@{\hspace{1.4cm}}l@{}}",
    ]
    previous_group: int | None = None
    for entry in entries:
        group = int(entry["group"])
        if previous_group is not None and group != previous_group:
            lines.append(r"\\[-0.15em]")
        ####
        copies = int(entry["copies"])
        mail_stop = str(entry["mail_stop"])
        recipient = _distribution_recipient(entry)
        lines.append(rf"{copies} & {mail_stop} & {recipient} \\")
        previous_group = group
    ####
    blank = payload["blank_page"]
    lines.extend(
        [
            r"\end{tabular}",
            r"\end{center}",
            r"\endgroup",
            r"\clearpage",
            f"% Source PDF page {blank['source_pdf_page']}; source manual page {blank['source_manual_page']}.",
            r"\thispagestyle{plain}",
            r"\null",
            r"\vfill",
            r"\begin{center}",
            rf"  \itshape {blank['text']}",
            r"\end{center}",
            r"\vfill",
            r"\null",
            "",
        ]
    )
    DISTRIBUTION_OUTPUT.write_text("\n".join(lines))
####


def main() -> None:
    _write_references()
    _write_index()
    _write_distribution()
    print("Generated References, Index, and Distribution LaTeX from metadata.")
####


if __name__ == "__main__":
    main()
####
