"""Validate and render the metadata-driven fidelity parity contract."""

from __future__ import annotations

import argparse
import hashlib
import json
from pathlib import Path
from typing import Any

import yaml

ROOT = Path(__file__).resolve().parents[1]
CATALOG = ROOT / "verification/fidelity_parity.yaml"
OUTPUT = ROOT / "verification/generated/fidelity_parity_contracts.json"
PROBLEM_CATALOG = ROOT / "verification/problem_generation.yaml"
####


def _sha256(path: Path) -> str:
    return hashlib.sha256(path.read_bytes()).hexdigest()
####


def build_contract(catalog_path: Path = CATALOG) -> dict[str, Any]:
    """Return the normalized contract and fail on missing source inputs."""

    payload = yaml.safe_load(catalog_path.read_text(encoding="utf-8"))
    problem_catalog = yaml.safe_load(PROBLEM_CATALOG.read_text(encoding="utf-8"))
    generated_outputs = {str(scenario["output"]) for scenario in problem_catalog["scenarios"]}
    required = tuple(payload["required_fields"])
    families: list[dict[str, Any]] = []
    for family in payload["families"]:
        missing = [field for field in required if field not in family]
        if missing:
            raise ValueError(f"{family['id']} missing parity fields: {', '.join(missing)}")
        if family["reduction_kind"] not in {"point-mass-3dof", "kinematic-3-plus-3-dof"}:
            raise ValueError(f"{family['id']} has unsupported reduction kind: {family['reduction_kind']}")
        problems = {name: str(ROOT / family[name]) for name in ("point_mass_problem", "bridge_source_problem", "constrained_rigid_problem")}
        unregistered = [
            str(Path(value).relative_to(ROOT))
            for value in problems.values()
            if str(Path(value).relative_to(ROOT)) not in generated_outputs
        ]
        if unregistered:
            raise ValueError(
                f"{family['id']} parity problems are not generated by {PROBLEM_CATALOG.relative_to(ROOT)}: "
                + ", ".join(unregistered)
            )
        missing_paths = [name for name, value in problems.items() if not Path(value).is_file()]
        missing_tables = [path for path in family["source_tables"] if not (ROOT / path).is_file()]
        if missing_paths or missing_tables:
            raise ValueError(f"{family['id']} missing inputs: problems={missing_paths}, tables={missing_tables}")
        families.append({
            "id": str(family["id"]),
            "scenario_id": str(family["scenario_id"]),
            "status": str(family["status"]),
            "reduction_kind": str(family["reduction_kind"]),
            "parity_tolerances": family["parity_tolerances"],
            "continuity_tolerances": family["continuity_tolerances"],
            "blocker": family.get("blocker"),
            "unit_profiles": {"point_mass": family["point_output_units"], "rigid_body": family["rigid_output_units"]},
            "state_mapping": family["state_mapping"],
            "inputs": {
                name: {"path": str(Path(value).relative_to(ROOT)), "sha256": _sha256(Path(value))}
                for name, value in problems.items()
            },
            "source_tables": [{"path": path, "sha256": _sha256(ROOT / path)} for path in family["source_tables"]],
            **{field: family[field] for field in required if field != "source_tables"},
        })
    return {"schema_version": 1, "catalog": str(catalog_path.relative_to(ROOT)), "families": families}
####


def generate(catalog_path: Path = CATALOG, output: Path = OUTPUT) -> Path:
    """Write the deterministic machine-readable parity contract."""

    output.parent.mkdir(parents=True, exist_ok=True)
    output.write_text(json.dumps(build_contract(catalog_path), indent=2, sort_keys=True) + "\n", encoding="utf-8")
    return output
####


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    expected = json.dumps(build_contract(), indent=2, sort_keys=True) + "\n"
    if args.check:
        if not OUTPUT.is_file() or OUTPUT.read_text(encoding="utf-8") != expected:
            raise SystemExit(f"stale generated parity contract: {OUTPUT}")
        return 0
    generate()
    return 0
####


if __name__ == "__main__":
    raise SystemExit(main())
####
