from __future__ import annotations

from collections import defaultdict
from pathlib import Path
from typing import Any

import yaml

ROOT = Path(__file__).resolve().parents[1]
METADATA = ROOT / "metadata" / "output_variables_appendix.yaml"
OUTPUT = ROOT / "backmatter" / "appendix_output_variables.tex"


def _load_entries() -> list[dict[str, Any]]:
    with METADATA.open() as handle:
        payload = yaml.safe_load(handle)
    ####
    reference = payload["appendix_output_variable_reference"]
    return list(reference["entries"])
####


def _description(entry: dict[str, Any]) -> str:
    description = str(entry["description_latex"])
    references = list(entry.get("references", []))
    if references:
        return f"{description} (\\cref{{{','.join(references)}}})."
    ####
    return f"{description}."
####


def _math(value: str) -> str:
    return f"\\({value}\\)" if value else ""
####


def _row(entry: dict[str, Any]) -> str:
    return " & ".join(
        [
            f"\\statevar{{{entry['name']}}}",
            _math(str(entry["symbol_latex"])),
            _description(entry),
            _math(str(entry["default_units_latex"])),
            str(entry["decimal_places"]),
        ]
    ) + " \\\\"
####


def _table_lines(entries: list[dict[str, Any]], source_page: int) -> list[str]:
    header = (
        "\\shortstack[l]{\\textbf{Variable}\\\\\\textbf{Name}} & "
        "\\textbf{Symbol} & \\textbf{Description} & "
        "\\shortstack{\\textbf{Default}\\\\\\textbf{Units}} & "
        "\\shortstack{\\textbf{Decimal}\\\\\\textbf{Places}} \\\\"
    )
    lines = [
        f"% Source PDF page {source_page}; source manual page A-{source_page - 281}.",
        r"\begin{longtable}{@{}>{\raggedright\arraybackslash}p{0.82in}>{\raggedright\arraybackslash}p{1.08in}>{\raggedright\arraybackslash}p{3.02in}>{\centering\arraybackslash}p{0.68in}>{\centering\arraybackslash}p{0.52in}@{}}",
        r"\toprule",
        header,
        r"\midrule",
        r"\endfirsthead",
        r"\toprule",
        header,
        r"\midrule",
        r"\endhead",
        r"\bottomrule",
        r"\endlastfoot",
    ]
    lines.extend(_row(entry) for entry in entries)
    lines.append(r"\end{longtable}")
    return lines
####


def main() -> None:
    entries = _load_entries()
    grouped: dict[int, list[dict[str, Any]]] = defaultdict(list)
    for entry in entries:
        grouped[int(entry["source_pdf_page"])].append(entry)
    ####

    lines = [
        "% Generated from metadata/output_variables_appendix.yaml.",
        "% Do not edit this file directly; run tools/generate_appendix_output_variables.py.",
        r"\begingroup",
        r"\footnotesize",
        r"\setlength{\tabcolsep}{3pt}",
        r"\renewcommand{\arraystretch}{1.06}",
    ]
    for source_page in range(282, 293):
        lines.extend(_table_lines(grouped[source_page], source_page))
        if source_page < 292:
            lines.append(r"\clearpage")
        ####
    ####
    lines.extend([r"\endgroup", ""])
    OUTPUT.write_text("\n".join(lines))
    print(f"Generated {OUTPUT.relative_to(ROOT)} with {len(entries)} entries on 11 source-mapped pages.")
####


if __name__ == "__main__":
    main()
####
