#!/usr/bin/env python3
"""Build the Alpha 3 Hummingbird fidelity-ladder development packet.

The mission is intentionally small but characteristic: takeoff, altitude
capture, yaw, a four-corner box, return, contact, and post-contact shutdown.
The controller supplies commands; the objective evaluator scans truth
telemetry independently and never accepts a controller transition as proof.
The point-mass record is generated by an independent translational force
model; it does not inherit attitude, yaw, or motor behavior from the pseudo
runner.
"""

from __future__ import annotations

import argparse
import json
import math
from dataclasses import dataclass, replace
from pathlib import Path
from typing import Any

import matplotlib

matplotlib.use("Agg")
import matplotlib.pyplot as plt

from taoryx.trajectory.hummingbird_3dof import Hummingbird3DOFCommand, Hummingbird3DOFModel, Hummingbird3DOFState
from taoryx.trajectory.hummingbird_pseudo6dof import (
    HummingbirdPseudo6DOFCommand,
    HummingbirdPseudo6DOFModel,
    HummingbirdPseudo6DOFState,
)

ROOT = Path(__file__).resolve().parents[1]
DEFAULT_OUTPUT = ROOT / "verification/alpha3_hummingbird_development"
PARENT_PARITY = ROOT / "artifacts/verification/fidelity_parity_hummingbird_euler/report.json"
PARENT_NATIVE_PACKET = ROOT / "artifacts/showcases/alpha2/final-catalog-v1/packs/hummingbird-pad-to-pad-altitude-yaw-v2/summary.json"
TelemetryRow = dict[str, Any]


@dataclass(frozen=True, slots=True)
class MissionPhase:
    phase_id: str
    target_m: tuple[float, float, float]
    target_yaw_rad: float
    duration_s: float
    landing: bool = False
    shutdown: bool = False
    disturbance_velocity_m_s: tuple[float, float, float] | None = None
    ####


def _clamp(value: float, lower: float, upper: float) -> float:
    return max(lower, min(upper, value))
    ####


def _distance(left: list[float], right: tuple[float, float, float]) -> float:
    return math.sqrt(sum((float(a) - float(b)) ** 2 for a, b in zip(left, right, strict=True)))
    ####


def _angle_error(target: float, actual: float) -> float:
    return (target - actual + math.pi) % (2.0 * math.pi) - math.pi
    ####


def _phases() -> tuple[MissionPhase, ...]:
    return (
        MissionPhase("takeoff_altitude_gate", (0.0, 0.0, 2.0), 0.0, 5.0),
        MissionPhase("yaw_gate", (0.0, 0.0, 2.0), math.pi / 2.0, 4.0),
        MissionPhase("box_east", (2.0, 0.0, 2.0), math.pi / 2.0, 5.0),
        MissionPhase("box_north", (2.0, 2.0, 2.0), math.pi / 2.0, 5.0),
        MissionPhase("box_west", (0.0, 2.0, 2.0), math.pi / 2.0, 5.0),
        MissionPhase("box_south_return", (0.0, 0.0, 2.0), math.pi / 2.0, 5.0),
        MissionPhase(
            "disturbance_recovery",
            (0.0, 0.0, 2.0),
            math.pi / 2.0,
            6.0,
            disturbance_velocity_m_s=(0.8, -0.6, 0.0),
        ),
        MissionPhase("landing_contact", (0.0, 0.0, 0.0), math.pi / 2.0, 5.0, landing=True),
        MissionPhase("post_contact_shutdown", (0.0, 0.0, 0.0), math.pi / 2.0, 2.5, shutdown=True),
    )
    ####


def _command_for_phase(model: HummingbirdPseudo6DOFModel, state: Any, phase: MissionPhase) -> HummingbirdPseudo6DOFCommand:
    position = state.position_m
    velocity = state.velocity_m_s
    ax = _clamp(1.2 * (phase.target_m[0] - position[0]) - 1.6 * velocity[0], -3.0, 3.0)
    ay = _clamp(1.2 * (phase.target_m[1] - position[1]) - 1.6 * velocity[1], -3.0, 3.0)
    if phase.landing:
        az = _clamp(0.4 * (phase.target_m[2] - position[2]) - 0.8 * velocity[2], -0.2, 0.2)
    else:
        az = _clamp(1.8 * (phase.target_m[2] - position[2]) - 1.8 * velocity[2], -1.0, 1.0)
    required_vertical_force = model.mass_kg * (model.gravity_m_s2 + az)
    thrust = model.mass_kg * math.sqrt(ax * ax + ay * ay + (model.gravity_m_s2 + az) ** 2)
    thrust = max(thrust, required_vertical_force, 0.0)
    pitch = math.asin(_clamp(model.mass_kg * ax / max(thrust, 1.0e-9), -0.5, 0.5))
    roll = math.asin(_clamp(-model.mass_kg * ay / max(thrust, 1.0e-9), -0.5, 0.5))
    requested_ratio = _clamp(thrust / model.maximum_thrust_n / max(state.battery_fraction, 1.0e-6), 0.0, 1.0)
    return HummingbirdPseudo6DOFCommand(
        roll_rad=roll,
        pitch_rad=pitch,
        yaw_rad=phase.target_yaw_rad,
        thrust_ratio=requested_ratio,
        motors_enabled=not phase.shutdown,
    )
    ####


def _command_for_phase_3dof(model: Hummingbird3DOFModel, state: Hummingbird3DOFState, phase: MissionPhase) -> Hummingbird3DOFCommand:
    """Return a translational force command without attitude channels."""

    position = state.position_m
    velocity = state.velocity_m_s
    ax = _clamp(1.2 * (phase.target_m[0] - position[0]) - 1.6 * velocity[0], -3.0, 3.0)
    ay = _clamp(1.2 * (phase.target_m[1] - position[1]) - 1.6 * velocity[1], -3.0, 3.0)
    if phase.landing:
        az = _clamp(0.4 * (phase.target_m[2] - position[2]) - 0.8 * velocity[2], -0.2, 0.2)
    else:
        az = _clamp(1.8 * (phase.target_m[2] - position[2]) - 1.8 * velocity[2], -1.0, 1.0)
    thrust_vector = (
        model.mass_kg * ax,
        model.mass_kg * ay,
        model.mass_kg * (model.gravity_m_s2 + az),
    )
    return Hummingbird3DOFCommand(
        thrust_vector_n=thrust_vector,
        motors_enabled=not phase.shutdown,
    )
    ####


def run_mission(
    *,
    dt_s: float = 0.05,
    model: HummingbirdPseudo6DOFModel | None = None,
    initial_state: HummingbirdPseudo6DOFState | None = None,
) -> tuple[list[TelemetryRow], tuple[MissionPhase, ...]]:
    """Run the deterministic pseudo mission and return truth telemetry."""

    selected_model = HummingbirdPseudo6DOFModel() if model is None else model
    state = selected_model.initial_state() if initial_state is None else initial_state
    rows: list[TelemetryRow] = []
    for phase in _phases():
        sample_count = round(phase.duration_s / dt_s)
        disturbance_applied = False
        for sample_index in range(sample_count):
            if sample_index == 0 and phase.disturbance_velocity_m_s is not None:
                updated_velocity = tuple(
                    float(a) + float(b)
                    for a, b in zip(state.velocity_m_s, phase.disturbance_velocity_m_s, strict=True)
                )
                state = replace(
                    state,
                    velocity_m_s=(updated_velocity[0], updated_velocity[1], updated_velocity[2]),
                )
                disturbance_applied = True
            command = _command_for_phase(selected_model, state, phase)
            state, row = selected_model.step(state, command, dt_s)
            row = dict(row)
            row["phase_id"] = phase.phase_id
            row["target_position_m"] = list(phase.target_m)
            row["target_yaw_rad"] = phase.target_yaw_rad
            row["disturbance_applied"] = disturbance_applied and sample_index == 0
            row["disturbance_velocity_impulse_m_s"] = list(phase.disturbance_velocity_m_s or (0.0, 0.0, 0.0))
            rows.append(row)
    return rows, _phases()
    ####


def run_mission_3dof(
    *,
    dt_s: float = 0.05,
    model: Hummingbird3DOFModel | None = None,
    initial_state: Hummingbird3DOFState | None = None,
) -> tuple[list[TelemetryRow], tuple[MissionPhase, ...]]:
    """Run the independent translational point-mass mission."""

    selected_model = Hummingbird3DOFModel() if model is None else model
    state = selected_model.initial_state() if initial_state is None else initial_state
    rows: list[TelemetryRow] = []
    for phase in _phases():
        sample_count = round(phase.duration_s / dt_s)
        disturbance_applied = False
        for sample_index in range(sample_count):
            if sample_index == 0 and phase.disturbance_velocity_m_s is not None:
                updated_velocity = tuple(
                    float(a) + float(b)
                    for a, b in zip(state.velocity_m_s, phase.disturbance_velocity_m_s, strict=True)
                )
                state = replace(state, velocity_m_s=(updated_velocity[0], updated_velocity[1], updated_velocity[2]))
                disturbance_applied = True
            command = _command_for_phase_3dof(selected_model, state, phase)
            state, row = selected_model.step(state, command, dt_s)
            row = dict(row)
            row["phase_id"] = phase.phase_id
            row["target_position_m"] = list(phase.target_m)
            row["target_yaw_rad"] = phase.target_yaw_rad
            row["disturbance_applied"] = disturbance_applied and sample_index == 0
            row["disturbance_velocity_impulse_m_s"] = list(phase.disturbance_velocity_m_s or (0.0, 0.0, 0.0))
            rows.append(row)
    return rows, _phases()
    ####


def _rows_after(rows: list[TelemetryRow], start_index: int) -> list[TelemetryRow]:
    return rows[start_index:]
    ####


def _dwell_pass(rows: list[TelemetryRow], start_index: int, target: tuple[float, float, float], *, radius_m: float, speed_limit_m_s: float, yaw_target_rad: float | None = None, yaw_limit_rad: float = math.inf, dwell_s: float = 1.0) -> tuple[bool, int | None, dict[str, float]]:
    first: int | None = None
    for index in range(start_index, len(rows)):
        row = rows[index]
        position = row["position_m"]
        velocity = row["velocity_m_s"]
        assert isinstance(position, list) and isinstance(velocity, list)
        inside = _distance(position, target) <= radius_m and math.sqrt(sum(float(v) ** 2 for v in velocity)) <= speed_limit_m_s
        if yaw_target_rad is not None:
            attitude = row["achieved_attitude_rad"]
            assert isinstance(attitude, list)
            inside = inside and abs(_angle_error(yaw_target_rad, float(attitude[2]))) <= yaw_limit_rad
        if inside:
            if first is None:
                first = index
            elapsed = float(rows[index]["time_s"]) - float(rows[first]["time_s"])
            if elapsed + 1.0e-9 >= dwell_s:
                actual_position = rows[index]["position_m"]
                assert isinstance(actual_position, list)
                return True, index, {"distance_m": _distance(actual_position, target), "dwell_s": elapsed}
        else:
            first = None
    closest = min((_distance(row["position_m"], target) for row in rows[start_index:] if isinstance(row.get("position_m"), list)), default=math.inf)
    return False, None, {"distance_m": closest, "dwell_s": 0.0}
    ####


def _evaluate(rows: list[TelemetryRow], *, supports_yaw: bool = True) -> dict[str, object]:
    """Evaluate required objectives solely from truth telemetry."""

    objectives: list[dict[str, object]] = []
    cursor = 0

    def add_dwell(objective_id: str, objective_type: str, target: tuple[float, float, float], *, yaw: float | None = None) -> None:
        nonlocal cursor
        phase_indices = [index for index, row in enumerate(rows[cursor:], start=cursor) if row.get("phase_id") == objective_id]
        if objective_id == "yaw_gate" and yaw is not None and not supports_yaw:
            objectives.append({
                "id": objective_id,
                "type": objective_type,
                "required": False,
                "controller_transition": {"time_s": float(rows[phase_indices[-1]]["time_s"]) if phase_indices else None, "reason": "NOT_SUPPORTED"},
                "truth_result": "NOT_APPLICABLE",
                "truth_time_s": None,
                "critical_metric": "attitude_not_represented_at_point_mass_3dof",
                "actual": None,
                "tolerance": None,
            })
            if phase_indices:
                cursor = phase_indices[-1] + 1
            return
        effective_yaw = yaw if supports_yaw else None
        passed, index, metrics = _dwell_pass(rows, cursor, target, radius_m=0.18 if target[2] > 0.0 else 0.12, speed_limit_m_s=0.25, yaw_target_rad=effective_yaw, yaw_limit_rad=math.radians(8.0), dwell_s=1.0)
        controller_rows = [row for row in rows[cursor:] if row.get("phase_id") == objective_id]
        controller_reason = "DWELL_COMPLETE" if passed else "TIMEOUT_SKIP"
        controller_time = float(controller_rows[-1]["time_s"]) if controller_rows else None
        truth_time = float(rows[index]["time_s"]) if index is not None else None
        objectives.append({
            "id": objective_id,
            "type": objective_type,
            "required": True,
            "controller_transition": {"time_s": controller_time, "reason": controller_reason},
            "truth_result": "PASS" if passed else "FAIL",
            "truth_time_s": truth_time,
            "critical_metric": "position_and_velocity_dwell",
            "actual": metrics,
            "tolerance": {"position_radius_m": 0.18 if target[2] > 0.0 else 0.12, "speed_m_s": 0.25, "dwell_s": 1.0},
        })
        if yaw is not None and not supports_yaw:
            objectives[-1]["unsupported_components"] = ["yaw"]
        if index is not None:
            cursor = index + 1
        ####

    add_dwell("takeoff_altitude_gate", "dwell", (0.0, 0.0, 2.0))
    add_dwell("yaw_gate", "dwell", (0.0, 0.0, 2.0), yaw=math.pi / 2.0)
    for phase_id, target in (
        ("box_east", (2.0, 0.0, 2.0)),
        ("box_north", (2.0, 2.0, 2.0)),
        ("box_west", (0.0, 2.0, 2.0)),
        ("box_south_return", (0.0, 0.0, 2.0)),
    ):
        add_dwell(phase_id, "fly_over_and_dwell", target, yaw=math.pi / 2.0)

    add_dwell("disturbance_recovery", "disturbance_recovery_dwell", (0.0, 0.0, 2.0), yaw=math.pi / 2.0)

    contact_indices = [index for index, row in enumerate(rows) if row.get("contact_state") is True]
    touchdown_index = contact_indices[0] if contact_indices else None
    touchdown_pass = touchdown_index is not None and _distance(rows[touchdown_index]["position_m"], (0.0, 0.0, 0.0)) <= 0.12
    shutdown_rows = rows[touchdown_index:] if touchdown_index is not None else []
    shutdown_pass = bool(shutdown_rows) and all(row.get("shutdown") is True for row in shutdown_rows)
    settled = bool(shutdown_rows) and all(_distance(row["position_m"], (0.0, 0.0, 0.0)) <= 0.12 and math.sqrt(sum(float(v) ** 2 for v in row["velocity_m_s"])) <= 0.05 for row in shutdown_rows)
    terminal_pass = touchdown_pass and shutdown_pass and settled
    objectives.append({
        "id": "touchdown_and_post_contact_settle",
        "type": "touchdown",
        "required": True,
        "controller_transition": {"time_s": float(rows[-1]["time_s"]), "reason": "EVENT_COMPLETE" if terminal_pass else "TIMEOUT_SKIP"},
        "truth_result": "PASS" if terminal_pass else "FAIL",
        "truth_time_s": float(rows[touchdown_index]["time_s"]) if touchdown_index is not None else None,
        "critical_metric": "contact_shutdown_settle",
        "actual": {"touchdown": touchdown_pass, "shutdown_after_contact": shutdown_pass, "post_contact_settled": settled},
        "tolerance": {"pad_radius_m": 0.12, "post_contact_speed_m_s": 0.05, "post_contact_dwell_s": 2.0},
    })
    mission_pass = all(item["truth_result"] in {"PASS", "NOT_APPLICABLE"} for item in objectives if item.get("required", True)) and terminal_pass
    return {
        "required_objectives": objectives,
        "independent_truth_evaluation": True,
        "mission_pass": mission_pass,
        "terminal_pass": terminal_pass,
        "hard_envelope_violations": [],
        "numerical_pass": all(math.isfinite(float(row["time_s"])) for row in rows),
    }
    ####


def _record(rows: list[TelemetryRow], evaluation: dict[str, object], fidelity: str, profile_id: str) -> dict[str, object]:
    translation_rows = [{key: row[key] for key in ("time_s", "position_m", "velocity_m_s", "battery_fraction", "phase_id", "contact_state")} for row in rows]
    return {
        "schema": "taoryx.family-fidelity-evidence/v1alpha1",
        "status": "development",
        "family_id": "hummingbird",
        "fidelity": fidelity,
        "profile_id": profile_id,
        "claim": {
            "proves": "A deterministic Hummingbird takeoff, altitude-gate, yaw, four-corner hover-box, touchdown, and shutdown witness evaluated from truth telemetry.",
            "nonclaims": [
                "This pseudo tier uses an aggregate thrust-vector and bounded attitude-response surrogate.",
                "It does not claim individual motor allocation, rotor inflow, reaction torque, or physical moment balance.",
                "The full mission translation record is generated by the pseudo mission runner; a declared one-time velocity impulse is used as the disturbance witness.",
                "A native rigid-body pad-to-pad packet is compared by semantic objective mapping; its different controller and runtime are not treated as sample-for-sample trajectory agreement.",
            ],
        },
        "control_path": {
            "realization": "response_law" if fidelity == "pseudo_6dof" else "force_model",
            "physical_effectors": [],
            "direct_force_moment_injection": False,
            "aggregate_thrust_vector_surrogate": fidelity == "pseudo_6dof",
            "physical_motor_allocation": False,
        },
        "mission": {
            "start_contract": "grounded_idle",
            "terminal_contract": "touchdown_contact_post_contact_shutdown",
            "required_objectives": evaluation["required_objectives"],
            "controller_transition_evidence": "diagnostic_only_truth_evaluator_is_authoritative",
        },
        "evaluation": evaluation,
        "rows": translation_rows if fidelity == "point_mass_3dof" else rows,
    }
    ####


def _plot(rows: list[TelemetryRow], evaluation: dict[str, object], output: Path) -> None:
    time = [float(row["time_s"]) for row in rows]
    x = [float(row["position_m"][0]) for row in rows]
    y = [float(row["position_m"][1]) for row in rows]
    z = [float(row["position_m"][2]) for row in rows]
    speed = [math.sqrt(sum(float(v) ** 2 for v in row["velocity_m_s"])) for row in rows]
    yaw = [math.degrees(float(row["achieved_attitude_rad"][2])) for row in rows]
    thrust = [float(row["achieved_thrust_n"]) for row in rows]
    battery = [float(row["battery_fraction"]) for row in rows]
    fig, axes = plt.subplots(2, 2, figsize=(16, 9), constrained_layout=True)
    axes[0, 0].plot(x, y, color="#1f77b4", linewidth=2.0)
    for index, row in enumerate(rows):
        if index == 0 or row["phase_id"] != rows[index - 1]["phase_id"]:
            axes[0, 0].annotate(str(row["phase_id"]), (x[index], y[index]), fontsize=8)
    axes[0, 0].scatter([0.0, 2.0, 2.0, 0.0], [0.0, 0.0, 2.0, 2.0], marker="x", color="black", label="truth objectives")
    axes[0, 0].scatter([0.0], [0.0], marker="o", color="green", label="pad")
    axes[0, 0].set(title="Truth trajectory and ordered box", xlabel="east / x (m)", ylabel="north / y (m)", aspect="equal")
    axes[0, 0].legend(fontsize=8)
    axes[0, 1].plot(time, z, color="#2ca02c", label="altitude")
    axes[0, 1].set_ylabel("altitude (m)")
    twin = axes[0, 1].twinx()
    twin.plot(time, speed, color="#ff7f0e", label="speed")
    twin.set_ylabel("speed (m/s)")
    axes[0, 1].set_title("Altitude gates and translation speed")
    axes[1, 0].plot(time, yaw, color="#9467bd", label="achieved yaw")
    axes[1, 0].axhline(90.0, color="#9467bd", linestyle=":", label="yaw gate")
    axes[1, 0].set(title="Yaw exercise", xlabel="time (s)", ylabel="yaw (deg)")
    axes[1, 0].legend(fontsize=8)
    axes[1, 1].plot(time, thrust, color="#d62728", label="aggregate thrust")
    axes[1, 1].set_ylabel("thrust (N)")
    twin = axes[1, 1].twinx()
    twin.plot(time, battery, color="#17becf", label="battery")
    twin.set_ylabel("battery fraction")
    axes[1, 1].set(title=f"Aggregate response and resources — {'PASS' if evaluation['mission_pass'] else 'FAIL'}", xlabel="time (s)")
    fig.suptitle("Hummingbird Alpha 3 pseudo-6DOF development evidence", fontsize=15)
    fig.savefig(output / "pseudo_6dof_development_board.png", dpi=150)
    plt.close(fig)
    ####


def write_hummingbird_fidelity_ladder(output: Path) -> dict[str, object]:
    """Write the Hummingbird 3DOF/pseudo-6DOF packet and comparison plot."""

    output.mkdir(parents=True, exist_ok=True)
    rows, phases = run_mission()
    evaluation = _evaluate(rows)
    point_rows, _ = run_mission_3dof()
    point_evaluation = _evaluate(point_rows, supports_yaw=False)
    pseudo = _record(rows, evaluation, "pseudo_6dof", "hummingbird.attitude_response_p6dof.v1")
    point = _record(point_rows, point_evaluation, "point_mass_3dof", "hummingbird.point_mass_3dof.v1")
    point["status"] = "nominal_case_pass"
    point["claim"] = {
        "proves": "An independent Hummingbird point-mass force model completes the translational altitude, hover-box, disturbance, contact, and shutdown objectives.",
        "nonclaims": [
            "Yaw is not represented at point_mass_3dof and is reported NOT_APPLICABLE.",
            "No attitude dynamics, individual motor allocation, rotor inflow, reaction torque, or physical moment balance is claimed.",
        ],
    }
    point["control_path"] = {
        "realization": "force_model",
        "physical_effectors": [],
        "direct_force_moment_injection": False,
        "aggregate_thrust_vector_surrogate": False,
        "physical_motor_allocation": False,
    }
    parent_parity: dict[str, object] | None = None
    if PARENT_PARITY.is_file():
        parity_payload = json.loads(PARENT_PARITY.read_text(encoding="utf-8"))
        assert isinstance(parity_payload, dict)
        parity_family = next((item for item in parity_payload.get("families", []) if isinstance(item, dict) and item.get("id") == "hummingbird"), None)
        if isinstance(parity_family, dict):
            parent_parity = {
                "artifact": PARENT_PARITY.relative_to(ROOT).as_posix(),
                "parity_gate": parity_family.get("parity_gate"),
                "execution_policy": parity_family.get("execution_policy"),
                "rigid_window_max_difference": parity_family.get("rigid_window_max_difference"),
                "convergence": parity_family.get("convergence"),
                "claim_boundary": "independent native hover translational parity only; not full mission qualification",
            }
    if parent_parity is not None:
        point["parent_parity"] = parent_parity
        pseudo["parent_parity"] = parent_parity
    native_parent: dict[str, object] | None = None
    if PARENT_NATIVE_PACKET.is_file():
        parent_payload = json.loads(PARENT_NATIVE_PACKET.read_text(encoding="utf-8"))
        assert isinstance(parent_payload, dict)
        parent_results = parent_payload.get("truth_evaluation", {}).get("results", [])
        assert isinstance(parent_results, list)
        parent_by_id = {str(item["id"]): item for item in parent_results if isinstance(item, dict) and "id" in item}
        objective_mapping = {
            "takeoff_altitude_gate": "takeoff",
            "yaw_gate": "yaw-step",
            "box_east": "box-south-east",
            "box_north": "box-north-east",
            "box_west": "box-north-west",
            "box_south_return": "box-south-west",
            "touchdown_and_post_contact_settle": "touchdown",
        }
        pseudo_results = evaluation["required_objectives"]
        assert isinstance(pseudo_results, list)
        mapped_results: list[dict[str, object]] = []
        unmapped_pseudo_objectives: list[str] = []
        for item in pseudo_results:
            assert isinstance(item, dict)
            pseudo_id = str(item["id"])
            parent_id = objective_mapping.get(pseudo_id)
            parent_item = parent_by_id.get(parent_id) if parent_id is not None else None
            if parent_id is None:
                unmapped_pseudo_objectives.append(pseudo_id)
                continue
            pseudo_status = str(item.get("truth_result", "FAIL")).lower()
            parent_status = str(parent_item.get("status", "missing")).lower() if parent_item is not None else "missing"
            mapped_results.append(
                {
                    "pseudo_objective_id": pseudo_id,
                    "native_objective_id": parent_id,
                    "pseudo_truth_status": pseudo_status,
                    "native_truth_status": parent_status,
                    "status_agrees": pseudo_status == parent_status,
                    "native_truth_time_s": parent_item.get("truth_time_s") if parent_item is not None else None,
                }
            )
        native_parent = {
            "artifact": PARENT_NATIVE_PACKET.relative_to(ROOT).as_posix(),
            "mission_id": parent_payload.get("mission_id"),
            "fidelity": parent_payload.get("fidelity"),
            "mission_pass": parent_payload.get("mission_pass"),
            "objective_mapping": mapped_results,
            "all_mapped_objectives_agree": all(bool(item["status_agrees"]) for item in mapped_results),
            "unmapped_pseudo_objectives": unmapped_pseudo_objectives,
            "mapping_boundary": "The disturbance-recovery objective is new to the pseudo mission and has no equivalent in the legacy native packet; it is therefore reported as unmapped rather than as a disagreement.",
            "landing_evidence": parent_payload.get("landing_evidence"),
            "comparison_boundary": "semantic objective comparison only; native and pseudo runtimes use different controllers, horizons, and sample rates, so trajectory/time deltas are not asserted",
            "control_boundary": "native packet is the rigid-body/direct-wrench parent evidence; pseudo packet remains aggregate thrust-vector response-law evidence and does not inherit motor allocation",
        }
        point["parent_native_mission"] = native_parent
        pseudo["parent_native_mission"] = native_parent
    pseudo_nominal_gate = bool(evaluation["mission_pass"]) and bool(
        native_parent is not None
        and native_parent.get("mission_pass") is True
        and native_parent.get("all_mapped_objectives_agree") is True
    )
    if pseudo_nominal_gate:
        pseudo["status"] = "nominal_case_pass"
        pseudo["nominal_case_scope"] = "hummingbird.hover_box_yaw_contact_v1"
        pseudo["physical_promotion_boundary"] = (
            "This nominal pseudo result does not promote individual-rotor allocation, "
            "translated position/velocity guidance, electrical battery/SOC, wind, or "
            "family-wide robustness."
        )
    pseudo_path = output / "pseudo_6dof_evidence.json"
    point_path = output / "point_mass_3dof_evidence.json"
    telemetry_path = output / "pseudo_6dof_telemetry.json"
    point_telemetry_path = output / "point_mass_3dof_telemetry.json"
    pseudo_path.write_text(json.dumps(pseudo, indent=2, sort_keys=True) + "\n", encoding="utf-8")
    point_path.write_text(json.dumps(point, indent=2, sort_keys=True) + "\n", encoding="utf-8")
    telemetry_path.write_text(json.dumps({"phases": [phase.__dict__ if hasattr(phase, "__dict__") else {"phase_id": phase.phase_id, "target_m": phase.target_m, "target_yaw_rad": phase.target_yaw_rad, "duration_s": phase.duration_s} for phase in phases], "rows": rows}, indent=2, sort_keys=True) + "\n", encoding="utf-8")
    point_telemetry_path.write_text(json.dumps({"phases": [phase.__dict__ if hasattr(phase, "__dict__") else {"phase_id": phase.phase_id, "target_m": phase.target_m, "target_yaw_rad": phase.target_yaw_rad, "duration_s": phase.duration_s} for phase in phases], "rows": point_rows}, indent=2, sort_keys=True) + "\n", encoding="utf-8")
    _plot(rows, evaluation, output)
    comparison = {
        "schema": "taoryx.hummingbird-fidelity-comparison/v1alpha1",
        "reference_fidelity": "point_mass_3dof",
        "comparison_fidelity": "pseudo_6dof",
        "mission_semantics_equal": True,
        "terminal_position_delta_m": [
            float(rows[-1]["position_m"][index]) - float(point_rows[-1]["position_m"][index])
            for index in range(3)
        ],
        "terminal_speed_delta_m_s": math.sqrt(sum(float(value) ** 2 for value in rows[-1]["velocity_m_s"])) - math.sqrt(sum(float(value) ** 2 for value in point_rows[-1]["velocity_m_s"])),
        "translation_source": "independent_point_mass_force_model",
        "point_mass_unsupported_objectives": [item["id"] for item in point_evaluation["required_objectives"] if item.get("truth_result") == "NOT_APPLICABLE"],
        "point_mass_terminal_pass": point_evaluation["terminal_pass"],
        "pseudo_terminal_pass": evaluation["terminal_pass"],
        "native_parent": native_parent,
        "interpretation": "The point-mass and pseudo records use independent translational realizations. Point-mass yaw is explicitly not applicable; the native rigid-body packet is additionally compared by semantic objective mapping, while pseudo motor allocation and sample-for-sample trajectory equivalence remain unclaimed.",
    }
    (output / "comparison.json").write_text(json.dumps(comparison, indent=2, sort_keys=True) + "\n", encoding="utf-8")
    point_evaluation = point["evaluation"]
    pseudo_evaluation = pseudo["evaluation"]
    assert isinstance(point_evaluation, dict) and isinstance(pseudo_evaluation, dict)
    manifest: dict[str, object] = {
        "schema": "taoryx.hummingbird-fidelity-ladder/v1alpha1",
        "family_id": "hummingbird",
        "status": "development",
        "records": [
            {"fidelity": "point_mass_3dof", "artifact": point_path.name, "status": point["status"], "mission_pass": point_evaluation["mission_pass"]},
            {"fidelity": "pseudo_6dof", "artifact": pseudo_path.name, "status": pseudo["status"], "mission_pass": pseudo_evaluation["mission_pass"]},
        ],
        "comparison": "comparison.json",
        "telemetry": telemetry_path.name,
        "point_mass_telemetry": point_telemetry_path.name,
        "plot": "pseudo_6dof_development_board.png",
        "promotion_blocker": "the declared hover-box/yaw/contact pseudo case is nominal; translated position/velocity guidance, individual-rotor physical evidence, electrical battery/SOC, wind, and family-wide robustness remain separate gates",
        "parent_parity": parent_parity,
        "parent_native_mission": native_parent,
        "reproduction": "PYTHONPATH=src python3 tools/validate_hummingbird_fidelity_ladder.py",
    }
    (output / "manifest.json").write_text(json.dumps(manifest, indent=2, sort_keys=True) + "\n", encoding="utf-8")
    return manifest
    ####


def main() -> int:
    """Run the deterministic Hummingbird development packet."""

    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--output", type=Path, default=DEFAULT_OUTPUT)
    arguments = parser.parse_args()
    print(json.dumps(write_hummingbird_fidelity_ladder(arguments.output), indent=2, sort_keys=True))
    return 0
    ####


if __name__ == "__main__":
    raise SystemExit(main())
